codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
      engine:
        target: 80%
        flags:
          - engine
      sdk:
        target: 80%
        flags:
          - sdk
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  engine:
    paths:
      - engine/
    carryforward: false
  sdk:
    paths:
      - sdk/go/
    carryforward: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
