import {
  Incident,
  AstCommitIndex,
  AstFile,
  WebhookLog,
  TeamMember,
  ApiKey,
  MetricHourly,
  SystemHealthComponent,
} from '../types';

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-8094',
    title: 'nil pointer dereference in GetProfile()',
    status: 'CRITICAL',
    triggeringFile: 'pkg/handler/user.go:42',
    triggeringLine: 42,
    latencyMs: 740,
    commitHash: '8f3a1b4',
    branch: 'main',
    timestamp: '2026-07-28 12:04:18 UTC',
    goroutineId: 'goroutine 42 [running]',
    panicMessage: 'panic: runtime error: invalid memory address or nil pointer dereference',
    githubIssueUrl: 'https://github.com/algotyrnt/beacon-app/issues/104',
    githubIssueNumber: 104,
    rawStackTrace: `goroutine 42 [running]:
pkg/handler.(*UserHandler).GetProfile(0x0, 0xc0000a2000, 0x12)
	/workspace/pkg/handler/user.go:42 +0x3a
net/http.HandlerFunc.ServeHTTP(0x10b2d40, 0x1203400, 0xc0000a2000)
	/go/src/net/http/server.go:2166 +0x2f
github.com/algotyrnt/triage-go/sdk.RecoveryMiddleware.func1(0x1203400, 0xc0000a2000)
	/workspace/pkg/middleware/recovery.go:18 +0x85
net/http.(*ServeMux).ServeHTTP(0x1224100, 0x1203400, 0xc0000a2000)
	/go/src/net/http/server.go:2488 +0x184`,
    astSnippet: {
      functionName: 'GetProfile',
      file: 'pkg/handler/user.go',
      startLine: 38,
      lines: [
        { lineNum: 38, content: 'func (h *UserHandler) GetProfile(w http.ResponseWriter, r *http.Request) {' },
        { lineNum: 39, content: '	userID := r.URL.Query().Get("id")' },
        { lineNum: 40, content: '	ctx := r.Context()' },
        { lineNum: 41, content: '	// Unchecked struct pointer dereference on h.Repo' },
        { lineNum: 42, content: '	profile, err := h.Repo.FindUserByID(ctx, userID)', isTriggerLine: true },
        { lineNum: 43, content: '	if err != nil {' },
        { lineNum: 44, content: '		http.Error(w, err.Error(), http.StatusNotFound)' },
        { lineNum: 45, content: '		return' },
        { lineNum: 46, content: '	}' },
        { lineNum: 47, content: '	json.NewEncoder(w).Encode(profile)' },
        { lineNum: 48, content: '}' },
      ],
    },
    geminiAnalysis: {
      rootCause: 'Uninitialized Struct Receiver Field (Nil Pointer Dereference)',
      explanation:
        'The method receiver `h *UserHandler` was invoked with a `nil` `Repo` instance (0x0 pointer offset). Line 42 attempts to dereference `h.Repo.FindUserByID()`. Because `h.Repo` was never injected during route wireup in `pkg/api/router.go`, evaluating `h.Repo` causes immediate CPU page fault resulting in Go runtime panic.',
      severity: 'CRITICAL',
      recommendedFix:
        'Add a nil-check guard before accessing `h.Repo`, or enforce non-nil repository initialization in `NewUserHandler(repo UserRepository)`.',
    },
    suggestedPatch: `// Patch generated by Triage AST Engine
package handler

import (
	"errors"
	"net/http"
	"encoding/json"
)

func (h *UserHandler) GetProfile(w http.ResponseWriter, r *http.Request) {
	userID := r.URL.Query().Get("id")
	ctx := r.Context()
	
	// Triage Guard: Validate receiver dependency initialization
	if h == nil || h.Repo == nil {
		http.Error(w, "User service unavailable (uninitialized repository)", http.StatusInternalServerError)
		return
	}

	profile, err := h.Repo.FindUserByID(ctx, userID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}
	json.NewEncoder(w).Encode(profile)
}`,
  },
  {
    id: 'INC-8093',
    title: 'index out of range [3] with length 3 in ParseHeaders()',
    status: 'INVESTIGATING',
    triggeringFile: 'pkg/api/router.go:88',
    triggeringLine: 88,
    latencyMs: 320,
    commitHash: '8f3a1b4',
    branch: 'main',
    timestamp: '2026-07-28 11:42:10 UTC',
    goroutineId: 'goroutine 18 [running]',
    panicMessage: 'panic: runtime error: index out of range [3] with length 3',
    githubIssueUrl: 'https://github.com/algotyrnt/beacon-app/issues/102',
    githubIssueNumber: 102,
    rawStackTrace: `goroutine 18 [running]:
pkg/api.ParseHeaders(0xc0000e4100, 0x3, 0x3)
	/workspace/pkg/api/router.go:88 +0x62
pkg/api.(*Router).RouteRequest(0xc0000a4180, 0xc0000a2000)
	/workspace/pkg/api/router.go:45 +0x110`,
    astSnippet: {
      functionName: 'ParseHeaders',
      file: 'pkg/api/router.go',
      startLine: 84,
      lines: [
        { lineNum: 84, content: 'func ParseHeaders(parts []string) map[string]string {' },
        { lineNum: 85, content: '	res := make(map[string]string)' },
        { lineNum: 86, content: '	for i := 0; i <= len(parts); i++ {' },
        { lineNum: 87, content: '		// Off-by-one loop condition i <= len(parts)' },
        { lineNum: 88, content: '		pair := parts[i]', isTriggerLine: true },
        { lineNum: 89, content: '		res[pair] = "val"' },
        { lineNum: 90, content: '	}' },
        { lineNum: 91, content: '	return res' },
        { lineNum: 92, content: '}' },
      ],
    },
    geminiAnalysis: {
      rootCause: 'Off-By-One Array Index Access in For Loop',
      explanation:
        'Line 86 uses `i <= len(parts)` as the iteration boundary. For a slice with length 3, valid indices are 0, 1, and 2. When `i == 3`, accessing `parts[3]` causes a runtime panic.',
      severity: 'HIGH',
      recommendedFix: 'Change loop condition from `i <= len(parts)` to `i < len(parts)` or use `range`.',
    },
    suggestedPatch: `// Patch generated by Triage AST Engine
package api

func ParseHeaders(parts []string) map[string]string {
	res := make(map[string]string)
	for _, pair := range parts {
		res[pair] = "val"
	}
	return res
}`,
  },
  {
    id: 'INC-8092',
    title: 'send on closed channel in DispatchEvents()',
    status: 'RESOLVED',
    triggeringFile: 'pkg/worker/dispatcher.go:115',
    triggeringLine: 115,
    latencyMs: 120,
    commitHash: '7e2c9d1',
    branch: 'main',
    timestamp: '2026-07-28 09:15:33 UTC',
    goroutineId: 'goroutine 91 [running]',
    panicMessage: 'panic: send on closed channel',
    githubIssueUrl: 'https://github.com/algotyrnt/beacon-app/issues/99',
    githubIssueNumber: 99,
    rawStackTrace: `goroutine 91 [running]:
pkg/worker.(*Dispatcher).DispatchEvents(0xc000102000, 0xc000114080)
	/workspace/pkg/worker/dispatcher.go:115 +0x8e`,
    astSnippet: {
      functionName: 'DispatchEvents',
      file: 'pkg/worker/dispatcher.go',
      startLine: 110,
      lines: [
        { lineNum: 110, content: 'func (d *Dispatcher) DispatchEvents(evt Event) {' },
        { lineNum: 111, content: '	if d.stopped {' },
        { lineNum: 112, content: '		return' },
        { lineNum: 113, content: '	}' },
        { lineNum: 114, content: '	// Race condition: channel closed concurrently by Stop()' },
        { lineNum: 115, content: '	d.queue <- evt', isTriggerLine: true },
        { lineNum: 116, content: '}' },
      ],
    },
    geminiAnalysis: {
      rootCause: 'Unsynchronized Concurrent Channel Send After Close',
      explanation:
        'A worker goroutine attempted to send on `d.queue` after `d.Stop()` closed the channel without mutex synchronization on `d.stopped`.',
      severity: 'HIGH',
      recommendedFix: 'Protect `d.stopped` and channel operations with a `sync.RWMutex` or use a select block with context cancellation.',
    },
  },
  {
    id: 'INC-8091',
    title: 'sync: unlock of unlocked mutex in ReleaseLock()',
    status: 'RESOLVED',
    triggeringFile: 'pkg/cache/redis_store.go:64',
    triggeringLine: 64,
    latencyMs: 95,
    commitHash: '6a1d82f',
    branch: 'main',
    timestamp: '2026-07-28 07:02:00 UTC',
    goroutineId: 'goroutine 12 [running]',
    panicMessage: 'panic: sync: unlock of unlocked mutex',
    rawStackTrace: `goroutine 12 [running]:
pkg/cache.(*RedisStore).ReleaseLock(0xc000012090)
	/workspace/pkg/cache/redis_store.go:64 +0x24`,
    astSnippet: {
      functionName: 'ReleaseLock',
      file: 'pkg/cache/redis_store.go',
      startLine: 60,
      lines: [
        { lineNum: 60, content: 'func (s *RedisStore) ReleaseLock() {' },
        { lineNum: 61, content: '	defer s.mu.Unlock()' },
        { lineNum: 62, content: '	if s.closed {' },
        { lineNum: 63, content: '		s.mu.Unlock() // Double unlock!' },
        { lineNum: 64, content: '		return', isTriggerLine: true },
        { lineNum: 65, content: '	}' },
        { lineNum: 66, content: '}' },
      ],
    },
  },
];

export const MOCK_AST_FILES: AstFile[] = [
  {
    path: 'pkg',
    name: 'pkg',
    isDir: true,
    children: [
      {
        path: 'pkg/handler',
        name: 'handler',
        isDir: true,
        children: [
          {
            path: 'pkg/handler/user.go',
            name: 'user.go',
            totalFuncs: 6,
            totalLines: 142,
            sizeBytes: 4210,
            nodes: [
              {
                id: 'ast-node-1',
                name: 'UserHandler',
                kind: 'TypeSpec',
                pos: 120,
                end: 280,
                line: 14,
                signature: 'type UserHandler struct { Repo UserRepository; Cache CacheClient }',
              },
              {
                id: 'ast-node-2',
                name: 'GetProfile',
                kind: 'FuncDecl',
                pos: 410,
                end: 980,
                line: 38,
                receiver: '(h *UserHandler)',
                signature: 'func (h *UserHandler) GetProfile(w http.ResponseWriter, r *http.Request)',
                children: [
                  { id: 'node-2-1', name: 'r.URL.Query().Get("id")', kind: 'CallExpr', pos: 460, end: 495, line: 39 },
                  { id: 'node-2-2', name: 'h.Repo.FindUserByID(ctx, userID)', kind: 'CallExpr', pos: 540, end: 590, line: 42 },
                  { id: 'node-2-3', name: 'http.Error(w, err.Error(), ...)', kind: 'CallExpr', pos: 620, end: 680, line: 44 },
                ],
              },
              {
                id: 'ast-node-3',
                name: 'UpdateSettings',
                kind: 'FuncDecl',
                pos: 1010,
                end: 1540,
                line: 52,
                receiver: '(h *UserHandler)',
                signature: 'func (h *UserHandler) UpdateSettings(w http.ResponseWriter, r *http.Request)',
              },
            ],
          },
          {
            path: 'pkg/handler/auth.go',
            name: 'auth.go',
            totalFuncs: 4,
            totalLines: 98,
            sizeBytes: 2840,
            nodes: [
              {
                id: 'ast-node-4',
                name: 'AuthenticateToken',
                kind: 'FuncDecl',
                pos: 210,
                end: 620,
                line: 18,
                signature: 'func AuthenticateToken(tokenStr string) (*Claims, error)',
              },
            ],
          },
        ],
      },
      {
        path: 'pkg/api',
        name: 'api',
        isDir: true,
        children: [
          {
            path: 'pkg/api/router.go',
            name: 'router.go',
            totalFuncs: 8,
            totalLines: 210,
            sizeBytes: 6120,
            nodes: [
              {
                id: 'ast-node-5',
                name: 'ParseHeaders',
                kind: 'FuncDecl',
                pos: 1800,
                end: 2150,
                line: 84,
                signature: 'func ParseHeaders(parts []string) map[string]string',
              },
            ],
          },
        ],
      },
      {
        path: 'pkg/worker',
        name: 'worker',
        isDir: true,
        children: [
          {
            path: 'pkg/worker/dispatcher.go',
            name: 'dispatcher.go',
            totalFuncs: 5,
            totalLines: 160,
            sizeBytes: 4500,
          },
        ],
      },
    ],
  },
  {
    path: 'main.go',
    name: 'main.go',
    totalFuncs: 2,
    totalLines: 48,
    sizeBytes: 1280,
    nodes: [
      {
        id: 'ast-node-6',
        name: 'main',
        kind: 'FuncDecl',
        pos: 100,
        end: 850,
        line: 12,
        signature: 'func main()',
      },
    ],
  },
];

export const MOCK_COMMIT_INDEXES: AstCommitIndex[] = [
  {
    commitHash: '8f3a1b4',
    branch: 'main',
    parsedFilesCount: 28,
    totalFunctionsCount: 1420,
    status: 'INDEXED',
    indexedAt: '2026-07-28 12:00:00 UTC',
  },
  {
    commitHash: '7e2c9d1',
    branch: 'feat/auth-v2',
    parsedFilesCount: 26,
    totalFunctionsCount: 1395,
    status: 'INDEXED',
    indexedAt: '2026-07-28 09:10:00 UTC',
  },
  {
    commitHash: '6a1d82f',
    branch: 'main',
    parsedFilesCount: 25,
    totalFunctionsCount: 1380,
    status: 'INDEXED',
    indexedAt: '2026-07-27 18:45:12 UTC',
  },
];

export const MOCK_WEBHOOK_LOGS: WebhookLog[] = [
  {
    id: 'wh-9021',
    status: 'SUCCESS',
    statusCode: 200,
    eventType: 'panic.ingested',
    sourceIp: '34.120.45.12',
    timestamp: '2026-07-28 12:04:18.421 UTC',
    latencyMs: 14,
    headers: {
      'Content-Type': 'application/json',
      'X-Triage-Signature': 'sha256=9f8a3c2b1e4d7f6a',
      'X-Triage-SdkVersion': 'triage-go/v1.4.2',
      'User-Agent': 'Triage-Go-Agent/1.4',
    },
    requestBody: JSON.stringify(
      {
        incident_id: 'INC-8094',
        repository: 'algotyrnt/beacon-app',
        commit: '8f3a1b4',
        panic: 'runtime error: invalid memory address or nil pointer dereference',
        goroutine: 42,
        triggering_file: 'pkg/handler/user.go:42',
      },
      null,
      2
    ),
    responseBody: JSON.stringify(
      {
        status: 'accepted',
        ast_symbolicated: true,
        isolated_func: 'GetProfile',
        github_issue: 'https://github.com/algotyrnt/beacon-app/issues/104',
      },
      null,
      2
    ),
  },
  {
    id: 'wh-9020',
    status: 'SUCCESS',
    statusCode: 200,
    eventType: 'ast.reindexed',
    sourceIp: '140.82.112.4',
    timestamp: '2026-07-28 12:00:02.105 UTC',
    latencyMs: 28,
    headers: {
      'Content-Type': 'application/json',
      'X-GitHub-Event': 'push',
      'X-Triage-Signature': 'sha256=1a2b3c4d5e6f7a8b',
    },
    requestBody: JSON.stringify(
      {
        ref: 'refs/heads/main',
        head_commit: {
          id: '8f3a1b4',
          message: 'fix: update user handler dependencies',
          author: { name: 'algotyrnt', email: 'punjitha@gmail.com' },
        },
      },
      null,
      2
    ),
    responseBody: JSON.stringify({ status: 'reindexed', total_funcs: 1420 }, null, 2),
  },
  {
    id: 'wh-9019',
    status: 'UNAUTHORIZED',
    statusCode: 401,
    eventType: 'panic.ingested',
    sourceIp: '198.51.100.44',
    timestamp: '2026-07-28 10:15:22.080 UTC',
    latencyMs: 3,
    headers: {
      'Content-Type': 'application/json',
      'X-Triage-Signature': 'invalid_secret_key_hash',
    },
    requestBody: JSON.stringify({ error: 'invalid payload key signature' }, null, 2),
    responseBody: JSON.stringify({ error: '401 Unauthorized: Invalid API Key Signature' }, null, 2),
  },
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'usr-1',
    name: 'Punjitha (algotyrnt)',
    githubUsername: 'algotyrnt',
    avatarUrl: 'https://github.com/algotyrnt.png',
    role: 'Owner',
    scopes: ['repo:read', 'ast:write', 'incidents:manage', 'billing:admin'],
    lastActive: 'Active now',
    mfaEnabled: true,
  },
  {
    id: 'usr-2',
    name: 'Devon Vance',
    githubUsername: 'devonvance-go',
    role: 'Admin',
    scopes: ['repo:read', 'ast:write', 'incidents:manage'],
    lastActive: '2 hours ago',
    mfaEnabled: true,
  },
  {
    id: 'usr-3',
    name: 'Elena Rostova',
    githubUsername: 'erostova-sys',
    role: 'Member',
    scopes: ['repo:read', 'incidents:read'],
    lastActive: 'Yesterday',
    mfaEnabled: false,
  },
];

export const MOCK_API_KEYS: ApiKey[] = [
  {
    id: 'key-1',
    name: 'Production Cloud Run Engine Key',
    keyMasked: 'trj_live_9f8a3c2b...f6a',
    fullKey: 'trj_live_9f8a3c2b1e4d7f6a89201bcde',
    createdAt: '2026-05-10',
    lastUsed: '14 seconds ago',
    status: 'ACTIVE',
  },
  {
    id: 'key-2',
    name: 'Staging K8s Ingress Key',
    keyMasked: 'trj_stage_4a1b2c3d...90e',
    fullKey: 'trj_stage_4a1b2c3d4e5f6a7b8c90e',
    createdAt: '2026-06-15',
    lastUsed: '3 days ago',
    status: 'ACTIVE',
  },
];

export const MOCK_HOURLY_METRICS: MetricHourly[] = [
  { hourLabel: '00:00', panicCount: 1, avgLatencyMs: 140, astIndexTimeMs: 24 },
  { hourLabel: '02:00', panicCount: 0, avgLatencyMs: 0, astIndexTimeMs: 22 },
  { hourLabel: '04:00', panicCount: 2, avgLatencyMs: 210, astIndexTimeMs: 26 },
  { hourLabel: '06:00', panicCount: 0, avgLatencyMs: 0, astIndexTimeMs: 20 },
  { hourLabel: '08:00', panicCount: 4, avgLatencyMs: 180, astIndexTimeMs: 25 },
  { hourLabel: '10:00', panicCount: 3, avgLatencyMs: 320, astIndexTimeMs: 29 },
  { hourLabel: '12:00', panicCount: 2, avgLatencyMs: 740, astIndexTimeMs: 28 },
];

export const MOCK_SYSTEM_HEALTH: SystemHealthComponent[] = [
  {
    name: 'Go Runtime Ingestion Engine',
    service: 'Cloud Run / GCP us-central1',
    status: 'OPERATIONAL',
    latency: '14ms',
    detail: 'Symbolication worker pool healthy (12/12 pods active)',
  },
  {
    name: 'GCS AST Storage & Byte Indexer',
    service: 'Google Cloud Storage / AST Cache',
    status: 'OPERATIONAL',
    latency: '8ms',
    detail: '1,420 Go function signatures indexed for commit 8f3a1b4',
  },
  {
    name: 'Gemini 3.6 Diagnostic Client',
    service: 'Gemini AI API Proxy',
    status: 'OPERATIONAL',
    latency: '420ms',
    detail: 'Root Cause & Patch Generator operational',
  },
];
